#!/usr/bin/env python3
"""
harden_01_scaffold.py
Creates mechanical repo-hygiene files. Safe + idempotent.

USAGE:
  1. DRY_RUN = True  (default) -> preview only, writes nothing.
  2. DRY_RUN = False           -> creates missing files.
  3. Existing files are NEVER overwritten (skipped with a notice).

Run from the repo root:
  python harden_01_scaffold.py
"""

from pathlib import Path

# ----------------------------------------------------------------------
# TOGGLE THIS
# ----------------------------------------------------------------------
DRY_RUN = False
# ----------------------------------------------------------------------

REPO_ROOT = Path.cwd()

FILES = {
    "pyproject.toml": """\
[build-system]
requires = ["setuptools>=68", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "agentic-vuln-system"
version = "0.1.0"
description = "Agentic pipeline that filters dead-code vulnerabilities, prioritizes real-world threats, and tests AI-generated patches in isolated sandboxes."
readme = "README.md"
requires-python = ">=3.10"
license = { text = "MIT" }
authors = [{ name = "NehaAIML" }]
dependencies = [
    "requests",
]

[project.optional-dependencies]
dev = [
    "pytest",
    "pytest-cov",
    "responses",
    "ruff",
    "black",
    "mypy",
    "pre-commit",
]

[project.scripts]
vuln-triage = "run_pipeline:main"

[tool.pytest.ini_options]
testpaths = ["tests"]
addopts = "-q"

[tool.ruff]
line-length = 100
target-version = "py310"

[tool.black]
line-length = 100
target-version = ["py310"]

[tool.mypy]
python_version = "3.10"
ignore_missing_imports = true
""",
    "SECURITY.md": """\
# Security Policy

## Reporting a Vulnerability

Please open a private GitHub security advisory, or email the maintainer.
Do not open public issues for exploitable findings.

## Threat Model of This Tool

This project scans *other* repositories and executes AI-generated patches.
It is therefore itself a security-sensitive component.

>>> EDIT THIS SECTION — do not ship as-is <<<

- Sandbox mechanism: [ ] temp dir only  [ ] Docker  [ ] nsjail/firejail  [ ] VM
- Network access inside sandbox: [ ] enabled  [ ] disabled
- Resource limits (CPU/mem/disk): [ ] none  [ ] specified below
- Secrets exposed to generated code: [ ] possible  [ ] prevented

Until the above is filled in and verified, do not run this pipeline
against untrusted repositories or with production credentials present.

## Supported Versions

| Version | Supported |
|---------|-----------|
| main    | yes       |
""",
    "CONTRIBUTING.md": """\
# Contributing

1. Fork and branch from `main`.
2. `python -m venv .venv && source .venv/bin/activate`
3. `pip install -e .[dev]`
4. `pre-commit install`
5. `pytest`  — all tests must pass; new logic needs tests.
6. Open a PR with a conventional-commit title, e.g. `fix(scanners): ...`.

## Commit style
`type(scope): short subject` — types: feat, fix, docs, test, chore, ci, refactor.
""",
    ".pre-commit-config.yaml": """\
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-yaml
      - id: check-added-large-files
      - id: detect-private-key

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.6.9
    hooks:
      - id: ruff
        args: [--fix]
      - id: ruff-format

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.11.2
    hooks:
      - id: mypy
        additional_dependencies: [types-requests]
""",
    ".github/ISSUE_TEMPLATE/bug_report.md": """\
---
name: Bug report
about: Something is broken
---
**What happened**

**Expected**

**Repro steps / sample repo**

**Environment** (OS, Python, LLM provider)
""",
    ".github/ISSUE_TEMPLATE/feature_request.md": """\
---
name: Feature request
about: Suggest an idea
---
**Problem**

**Proposed solution**

**Alternatives considered**
""",
    ".github/workflows/ci.yml": """\
name: CI
on:
  push: { branches: [main] }
  pull_request:
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.10", "3.11", "3.12"]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - run: pip install -e .[dev]
      - run: pytest
      - run: ruff check .
""",
    "TODO.md": """\
# Repo Hardening TODO (generated by harden_01_scaffold.py)

These items require human judgment and were intentionally NOT automated.

## P0 — correctness / credibility
- [ ] Add mocked-response tests for `scanners/prioritization.py` (EPSS).
      Cover: happy path, timeout, 5xx, malformed JSON, missing CVE key.
- [ ] Fill in the real isolation model in `SECURITY.md` and verify it.
- [ ] Pin every dependency in `pyproject.toml` to match `requirements*.txt`.

## P1 — reproducibility
- [ ] Generate a lockfile (`uv lock` or `pip-compile`).
- [ ] Make retry cap configurable: env `MAX_REPAIR_ATTEMPTS` (default 3).
- [ ] Emit a structured JSON run report per pipeline run.

## P2 — evidence
- [ ] Add `benchmarks/` with results on one real pinned vulnerable OSS repo.
- [ ] Add a "Limitations" section to README.
- [ ] Document the dashboard: stack, launch command, screenshot.

## P3 — polish
- [ ] Use conventional commits going forward.
- [ ] Add a coverage badge to README.
- [ ] Add ADRs in `docs/adr/` for: AST vs runtime tracing; sandbox vs LLM-review.
""",
}


def main() -> None:
    print(f"Repo root : {REPO_ROOT}")
    print(f"DRY_RUN   : {DRY_RUN}")
    print("-" * 60)

    created, skipped = [], []

    for rel_path, content in FILES.items():
        target = REPO_ROOT / rel_path
        if target.exists():
            print(f"[SKIP]    {rel_path}  (already exists)")
            skipped.append(rel_path)
            continue

        if DRY_RUN:
            print(f"[WOULD CREATE] {rel_path}")
        else:
            target.parent.mkdir(parents=True, exist_ok=True)
            target.write_text(content, encoding="utf-8")
            print(f"[CREATED] {rel_path}")
            created.append(rel_path)

    print("-" * 60)
    print(f"Created : {len(created)}")
    print(f"Skipped : {len(skipped)}  (already present)")

    if DRY_RUN:
        print("\nDRY_RUN is ON — nothing was written.")
        print("Set DRY_RUN = False and run again to apply.")
    else:
        print("\nDone. Review with:  git status   and   git diff")


if __name__ == "__main__":
    main()
